export const AUTH_ERROR = {
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  REFRESH_INVALID: 'REFRESH_INVALID',
  REFRESH_REUSE: 'REFRESH_REUSE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NAME_REQUIRED: 'NAME_REQUIRED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];
